---
title: "Lab3"
author: "Yi Wang"
date: "2018Äê9ÔÂ26ÈÕ"
output: html_document
---
```{r}
library(ggplot2)
p  = ggplot()
library(gapminder)
data("gapminder")
p = geom_point(data = gapminder, 
               aes(x = gdpPercap,
                   y = lifeExp))
```

## problem 1
```{r}
curve(dnorm, from=-4, to=4, ylab="PDF", main="Pr(X <= -1)")
coord.x = c(-4,seq(-4,-1, by=0.1),-1)
coord.y = c(0,dnorm(seq(-4,-1, by=0.1)), 0)
polygon(coord.x, coord.y, col=2)
```
```{r}

x = seq(-4, 4, by = 0.01)
y = dnorm(x)
df = data.frame(x, y)
ggplot(data = df, aes(x = x, y = y)) + 
  geom_line() +
  geom_ribbon(data = df[df$x <= -1, ], aes(x, ymax = y, ymin = 0), fill = "red", color = "black", alpha = 1) +
  labs(y = "Density", title = "Pr(X <= -1)") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))

```

## Problem 2
```{r}
library(tidyverse)

g_2007 <- filter(gapminder,year == 2007)
x <- g_2007[g_2007$continent == "Europe" & g_2007$gdpPercap > 40000, ]
g_2007 %>%  
  ggplot(aes(x = gdpPercap, y = lifeExp)) +
  geom_point() +
  geom_text(data = x, label = x$country, col = "blue", size = 4.5, vjust = 1) +
  labs(x = "GDP per capita", y = "life expectancy") +
  theme_bw()
```

## Assignment problem 4
```{r}
g_2007 %>%
  ggplot(aes(x = gdpPercap, y = lifeExp)) +
  geom_point(shape = 1, size = 2, stroke = 1.3) +
  geom_rect(aes(xmin = 39000, xmax = 51000, ymin = 75, ymax = 85), fill = "red", alpha = 0.002)+
  annotate("text", x = 45000, y = 72, label = "Countries with \n highest GDP") +
  labs(x = "GDP per capita", y = "life expectancy") +
  theme_bw()
```

